<?php
//main User table model
//It was generated by CLI=> php artisan make:auth
//is used for authentication (login/password)
namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
//use Illuminate\Database\Eloquent\Model; //???? Added by me

use Zizaco\Entrust\Traits\EntrustUserTrait; //my

class User extends Authenticatable
{
    use EntrustUserTrait; //use Zizaco Entrust
	use Notifiable;
	

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'fb_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
